### ISSUE TITLE
碧蓝航线彗星

### ISSUE THREAD

**Issue by chinolanyun** [Zzzzzzyt/MoeRanker#15] opened 2024-08-06 02:56 UTC
舰B的彗星是谁家的啊，这看着也不C啊

![81a467398bc5fd171fe64f78bd67be08](https://github.com/user-attachments/assets/26e48cda-7ac9-4732-98a9-84bcc341d5c8)

**Comment by Zzzzzzyt** [comment] 2024-08-08 03:53
Duplicate of #3

**Closed by Zzzzzzyt** 2024-08-08 03:53 UTC
