### ISSUE TITLE
碧蓝航线：天鹰 和 碧蓝航线：神通 和 碧蓝航线：肇和 图片映射错误

### ISSUE THREAD

**Issue by Dax233** [Zzzzzzyt/MoeRanker#11] opened 2024-08-05 12:52 UTC
![5f27250754228843940a658867790dbd](https://github.com/user-attachments/assets/64a47d91-174b-405a-a01c-dd45786dccee)
![8faed7b4a5d58d3b5b4e57e84a4f6386](https://github.com/user-attachments/assets/4343fbe0-3b76-4ac8-85b2-4d77c41f5814)
![3a24d40cf531d678c4eaefd4ffcb7d8e](https://github.com/user-attachments/assets/3dc1732a-ec29-4967-897a-cc619afb232b)

**Comment by Zzzzzzyt** [comment] 2024-08-08 03:47
Duplicate of #3

**Closed by Zzzzzzyt** 2024-08-08 03:47 UTC
